name = "email"
main = "worker.js"
compatibility_date = "2025-05-20"

[[d1_databases]]
binding = "DB"
database_name = "mail_bucket"
database_id = "你的D1_ID"

[[r2_buckets]]
binding = "MAIL_BUCKET"
bucket_name = "mail-storage"

[vars]
# 多个域名用英文逗号分隔，第一个为主域名
MAIL_DOMAINS = "domain1.com,domain2.com,domain3.com"
ACCESS_PASSWORD = "你的访问密码"
